Service & Service Implementation added
ileanahi/doctors-office pull request #13
Opened 2023-02-05 03:59 UTC by VeronicaO27

2023-02-06 21:08 UTC, williamsc51 requested changes

2023-02-06 21:08 UTC, williamsc51 commented on src/main/java/com/capstone/doctorsOffice/entities/Patient.java
>  @Table(name = "patients")
I think this was an oversight (cut/paste) error.
The annotations were removed.
Need to put back the following annotations:
```
@Entity
 @Data
 @AllArgsConstructor
 @NoArgsConstructor
```

2023-02-06 21:08 UTC, williamsc51 commented on src/main/java/com/capstone/doctorsOffice/entities/Patient.java
Also, add the relationship to prescription
@OneToMany(mappedBy = "patient")
    private Set<Prescription> prescriptionSet;

2023-02-06 21:08 UTC, williamsc51 commented on src/main/java/com/capstone/doctorsOffice/entities/Prescription.java
> +
Change package for Entity import
should be
`import jakarta.persistence.*;`

2023-02-06 21:08 UTC, williamsc51 commented on src/main/java/com/capstone/doctorsOffice/entities/Prescription.java
> +@Data
Move @Data below @Table
should be
```
@Entity
@Table(name = "prescription")
@Data
```

2023-02-06 21:08 UTC, williamsc51 commented on src/main/java/com/capstone/doctorsOffice/dtos/PrescriptionDto.java
> +
Add the following annotations to create getter(), setter() and constructors
```
@Data
@AllArgsConstructor
@NoArgsConstructor
```

2023-02-06 21:08 UTC, williamsc51 commented on src/main/java/com/capstone/doctorsOffice/entities/Prescription.java
>  }
The DTO getter methods are not found because of the missing annotation in PrescriptionDto

See comment on PresciptionDto. You can uncomment these lines after the correction in the Dto class.

2023-02-06 21:08 UTC, williamsc51 commented on src/main/java/com/capstone/doctorsOffice/entities/Prescription.java
> +    private Set<Prescription> patients;
change the relationship here.
The prescription should be a ManytoOne relationship to Patients.
A Patient can have many prescriptions.
should be
```
    @ManyToOne
    @JoinColumn(name="patient_id")
    private Patient patient;
```

2023-02-06 21:08 UTC, williamsc51 commented on src/main/java/com/capstone/doctorsOffice/dtos/PrescriptionDto.java
> +import java.io.Serializable;
remove package import. not used in this class

2023-02-06 21:08 UTC, williamsc51 commented on src/main/java/com/capstone/doctorsOffice/services/PrescriptionService.java
> +
There are two methods to add a prescription. Remove one.

2023-02-06 21:08 UTC, williamsc51 commented on src/main/java/com/capstone/doctorsOffice/services/PrescriptionServiceImpl.java
> +
The `addNewPrescription(PrescriptionDto prescriptionDto)` is not doing anything. remove this one.

2023-02-06 21:08 UTC, williamsc51 commented on src/main/java/com/capstone/doctorsOffice/services/PrescriptionServiceImpl.java
> +        });
the update method set the Prescription properties from the Dto.
should be
```
            prescription.setPrescription(prescriptionDto.getPrescription());
            prescription.setFilled(prescriptionDto.getFilled());
            prescription.setDate(prescriptionDto.getDate(
```

2023-02-06 21:08 UTC, williamsc51 commented on src/main/java/com/capstone/doctorsOffice/controllers/PrescriptionController.java
> +
The `addNewPrescription()` in the Prescription service just return null.
change this to the `addPrescription` method from the Service class.

2023-02-06 21:08 UTC, williamsc51 commented on src/main/java/com/capstone/doctorsOffice/controllers/PrescriptionController.java
> +
The repository is not used in the Controller.
Remove
```
   @Autowired
     private PrescriptionRepository prescriptionRepository;
```

2023-02-08 02:19 UTC, williamsc51 approved these changes

2023-02-08 02:23 UTC, GRISONRF approved these changes

2023-02-08 02:34 UTC, merged