Update endpoint to add a new appointment
ileanahi/doctors-office pull request #17
Opened 2023-02-10 04:24 UTC by GRISONRF

In order to be able to get the appointment at the patient's profile, I had to change the `/new-appointment` to take the patient's id, and all the layers related to that.
I also changed the OneToOne relationship declaration between patient and appointment.

Note that we still need to change the code to add a doctor to the appointment.
Because of that, I commented a line at patient-profile so we don't get an error when rendering the page.

2023-02-11 04:14 UTC, asya-code reviewed
I am confused about passing in an id when we create a new appointment - where will the ID come from if we haven't submitted anything to the repository yet? 

My typical strategy was to create an appointment entity first, then save it in the database, and an ID will be autogenerated during saveAndFlash.

2023-02-11 15:08 UTC, williamsc51 requested changes

2023-02-11 15:08 UTC, williamsc51 commented on src/main/java/com/capstone/doctorsOffice/entities/Patient.java
>      private Doctor doctor;
Recommendation:
add a not null constraint to the Doctor relationship.
This will force a the need of a doctor ID when creating a patient.

Then for appointment we can pass the patient in and look up the doctor from the patient record.

2023-02-11 22:19 UTC, GRISONRF commented on src/main/java/com/capstone/doctorsOffice/entities/Patient.java
>      private Doctor doctor;
done

2023-02-11 22:54 UTC, asya-code approved these changes

2023-02-11 22:54 UTC, ileanahi approved these changes
Looks good

2023-02-14 17:51 UTC, williamsc51 commented
@GRISONRF I made some additional commits to the PR to get everything working so we can keep moving forward.

2023-02-14 17:51 UTC, williamsc51 approved these changes

2023-02-14 17:51 UTC, merged