Doctors views
ileanahi/doctors-office pull request #18
Opened 2023-02-11 15:07 UTC by ileanahi

Created Doctors pages

2023-02-13 00:08 UTC, williamsc51 requested changes

2023-02-13 00:08 UTC, williamsc51 commented on src/main/java/com/capstone/doctorsOffice/controllers/DoctorViewController.java
> +        System.out.println("**************** doctor view!!! ** -------------------");
This is not a big deal and you can choose to leave them if you like. But all the `System.out.println` I'm assuming is for debugging purpose. We wouldn't want to commit debug code into the repository.
Ideally we would remove all the `System.out.println`

2023-02-13 00:08 UTC, williamsc51 commented on src/main/java/com/capstone/doctorsOffice/controllers/DoctorViewController.java
> +    @GetMapping("/")
remove `"/"` let it just be an empty string `""`
With the current settings the url only works with the `/` at the end `http://localhost:8080/doctorView/`
The more natural url to list a collection is `http://localhost:8080/doctorView`

2023-02-13 00:08 UTC, williamsc51 commented on src/main/resources/templates/doctors.html
> +        <tr th:if="${doctors.isEmpty()}">
missing `table` tag. `tr` and `td` must be inside of a table tag.

The list is not rending correctly when displaying more that one doctor.
<img width="1065" alt="Screen Shot 2023-02-12 at 6 54 55 PM" src="https://user-images.githubusercontent.com/20031604/218344914-6b696ee6-1be0-4837-b961-51a55595f368.png">

2023-02-13 00:08 UTC, williamsc51 commented on src/main/resources/templates/doctor-profile.html
> +        <p><b>Next Appointment:</b></p>
Opinion:
If this is from the patient perspective, we do not want to display the doctors appointments and what patient the appointment is with to all patients.

We also should not display the doctor's patient list.
We should keep this page simple only displaying the doctor name and profession.

2023-02-14 16:37 UTC, williamsc51 requested changes

2023-02-14 16:37 UTC, williamsc51 commented on src/main/resources/templates/index.html
>              <li><a href="../">Pharmacy</a></li>
remove trailing `/`
```
@{'/doctorView'}
```

2023-02-14 16:37 UTC, williamsc51 commented on src/main/resources/templates/patient-profile.html
>                  <li><a href="../">Pharmacy</a></li>
remove trailing `/`
```
@{'/doctorView'}
```

2023-02-14 16:37 UTC, williamsc51 commented on src/main/java/com/capstone/doctorsOffice/controllers/DoctorViewController.java
> +        model.addAttribute("appointments", appointments);
remove lines 42 to 46.
We are no longer using those in the views. 
Remove lines 34 and 37 as well.

2023-02-14 16:37 UTC, williamsc51 commented on src/main/resources/templates/doctors.html
> +                </a>
The a tag have to be inside the td tag for it to work.
should be:
```
                    <td>
                        <a th:href="@{'/doctorView/' + ${doctor.id}}">
                            <span th:text="${doctor?.name} + ' - ' + ${doctor?.profession}"></span>
                        </a>
                    </td>
```

2023-02-18 04:56 UTC, asya-code approved these changes

2023-02-18 20:35 UTC, GRISONRF approved these changes

2023-02-18 20:35 UTC, mlandes-hackbright approved these changes

2023-02-18 20:38 UTC, merged