Implement Doctor controller, dto, and services
ileanahi/doctors-office pull request #7
Opened 2023-01-31 21:08 UTC by ileanahi

- Refactor Doctor entity to use doctorId instead of doctor
- Create doctor dto
- Remove Appointment repository from doctor repository

- Create Services:
- Get all doctors
- Get doctor by Id
- Add doctor
- Update doctor
- Delete doctor

2023-01-31 21:14 UTC, asya-code approved these changes

2023-01-31 23:47 UTC, VeronicaO27 approved these changes
Changes look good to me

2023-02-02 20:31 UTC, williamsc51 requested changes

2023-02-02 20:31 UTC, williamsc51 commented on src/main/java/com/capstone/doctorsOffice/entities/Doctor.java
> +        }
Its the dto value that should be assigned here.
should be:
```
if (doctorDto.getId() != null) {
             this.id = doctorDto.getId();
         }
```

Change the other two below as well.

2023-02-02 20:31 UTC, williamsc51 commented on src/main/java/com/capstone/doctorsOffice/controllers/DoctorController.java
> +    }
You should pass the PathVariable `id` the the `updateDoctor` method in the service and use that id to look up the doctor.

```
doctorService.updateDoctor(id, doctorDto);
```

You would need to then update the function signature in `DoctorService` and `DoctorServiceImpl`

2023-02-02 20:31 UTC, williamsc51 commented on src/main/java/com/capstone/doctorsOffice/services/DoctorServiceImpl.java
> +        Optional<Doctor> doctorOptional = doctorRepository.findById(doctorDto.getId());
Use the id passed in from the controller to look up the Doctor. Reason: The Dto id could be null.
```
public void updateDoctor(Long id, DoctorDto doctorDto) {
         Optional<Doctor> doctorOptional = doctorRepository.findById(id);
```

2023-02-04 02:10 UTC, williamsc51 approved these changes

2023-02-04 02:10 UTC, merged